version: '3.9'

services:
  influxdb:
    image: influxdb:2.7.11
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=Admin1234!
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=network-metrics
      - DOCKER_INFLUXDB_INIT_RETENTION=7d
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-token
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    ports:
      - "1883:1883"
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    depends_on:
      - influxdb
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  subscriber:
    build:
      context: .
      dockerfile: subscriber/Dockerfile
    container_name: subscriber
    environment:
      - INFLUXDB_BUCKET=network-metrics
      - INFLUXDB_ORG=my-org
      - INFLUXDB_TOKEN=my-token
    depends_on:
      - mqtt-broker
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  publisher:
    build:
      context: .
      dockerfile: publisher/Dockerfile
    container_name: publisher
    depends_on:
      - subscriber
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
